### ISSUE TITLE
RuntimeError: No compatible cmake generator installed on this machine

### ISSUE THREAD

**Issue by korfer** [novoic/surfboard#25]
Hi, I have following error message on windows 10 during pip install surfboard. Any way to fixit? Updating cmake doesn't help.

 ERROR: Command errored out with exit status 1:
     command: 'c:\users\пк\pycharmprojects\lungs-backend\venv\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ПК\\AppData\\Local\\Temp\\
pip-install-avso8t1w\\llvmlite_699981f89b3446759ede014768af2dca\\setup.py'"'"'; __file__='"'"'C:\\Users\\ПК\\AppData\\Local\\Temp\\pip-install-avso8t1w\\llvmlite_699981f89b3446759ede01476
8af2dca\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().
replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ПК\AppData\Local\Temp\pip-record-u4s4z6hm\install-record.txt' --s
ingle-version-externally-managed --compile --install-headers 'c:\users\пк\pycharmprojects\lungs-backend\venv\include\site\python3.9\llvmlite'
         cwd: C:\Users\ПК\AppData\Local\Temp\pip-install-avso8t1w\llvmlite_699981f89b3446759ede014768af2dca\
    Complete output (31 lines):
    running install
    running build
    got version from file C:\Users\ПК\AppData\Local\Temp\pip-install-avso8t1w\llvmlite_699981f89b3446759ede014768af2dca\llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87
f613bd414479d29d912771562'}
    running build_ext
    c:\users\пк\pycharmprojects\lungs-backend\venv\scripts\python.exe C:\Users\ПК\AppData\Local\Temp\pip-install-avso8t1w\llvmlite_699981f89b3446759ede014768af2dca\ffi\build.py
    -- Selecting Windows SDK version  to target Windows 10.0.19042.
    CMake Error at CMakeLists.txt:3 (project):
      Failed to run MSBuild command:
    
        MSBuild.exe
    
      to get the value of VCTargetsPath:
    
        РќРµ СѓРґР°РµС‚СЃСЏ РЅР°Р№С‚Рё СѓРєР°Р·Р°РЅРЅС‹Р№ С„Р°Р№Р»
    
    
    
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/РџРљ/AppData/Local/Temp/tmpt2d5fhn6/CMakeFiles/CMakeOutput.log".
    Trying generator 'Visual Studio 14 2015 Win64'
    Traceback (most recent call last):
      File "C:\Users\ПК\AppData\Local\Temp\pip-install-avso8t1w\llvmlite_699981f89b3446759ede014768af2dca\ffi\build.py", line 168, in <module>
        main()
      File "C:\Users\ПК\AppData\Local\Temp\pip-install-avso8t1w\llvmlite_699981f89b3446759ede014768af2dca\ffi\build.py", line 156, in main
        main_win32()
      File "C:\Users\ПК\AppData\Local\Temp\pip-install-avso8t1w\llvmlite_699981f89b3446759ede014768af2dca\ffi\build.py", line 88, in main_win32
        generator = find_win32_generator()
      File "C:\Users\ПК\AppData\Local\Temp\pip-install-avso8t1w\llvmlite_699981f89b3446759ede014768af2dca\ffi\build.py", line 84, in find_win32_generator
        raise RuntimeError("No compatible cmake generator installed on this machine")
    RuntimeError: No compatible cmake generator installed on this machine
    error: command 'c:\\users\\пк\\pycharmprojects\\lungs-backend\\venv\\scripts\\python.exe' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\пк\pycharmprojects\lungs-backend\venv\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\
Users\\ПК\\AppData\\Local\\Temp\\pip-install-avso8t1w\\llvmlite_699981f89b3446759ede014768af2dca\\setup.py'"'"'; __file__='"'"'C:\\Users\\ПК\\AppData\\Local\\Temp\\pip-install-avso8t1w\\l
lvmlite_699981f89b3446759ede014768af2dca\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setu
p; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ПК\AppData\Local\Temp\pip-record
-u4s4z6hm\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\пк\pycharmprojects\lungs-backend\venv\include\site\python3.9\llvmlite' Check the lo
gs for full command output.

**Comment by rlenain** [comment]
Hi there! And thanks for using Surfboard. A quick google leads me to believe that it might an issue with your LLVMLITE installation. Let us know if this helps!
